package com.github.aalbul.zio.telegram.domain

import io.circe.generic.extras.ConfiguredJsonCodec

import java.time.Instant

@ConfiguredJsonCodec(decodeOnly = true)
case class Message(
  messageId: Int,
  from: Option[User],
  senderChat: Option[Chat],
  date: Instant,
  chat: Chat,
  forwardFrom: Option[User],
  forwardFromChat: Option[Chat],
  forwardFromMessageId: Option[Int],
  forwardSignature: Option[String],
  forwardSenderName: Option[String],
  forwardDate: Option[Instant],
  isAutomaticForward: Option[Boolean],
  replyToMessage: Option[Message],
  viaBot: Option[User],
  editDate: Option[Instant],
  hasProtectedContent: Option[Boolean],
  mediaGroupId: Option[String],
  authorSignature: Option[String],
  text: Option[String],
  entities: Option[Seq[MessageEntity]],
  animation: Option[Animation],
  audio: Option[Audio],
  document: Option[Document],
  photo: Option[Seq[PhotoSize]],
  sticker: Option[Sticker],
  video: Option[Video],
  videoNote: Option[VideoNote],
  voice: Option[Voice],
  caption: Option[String],
  captionEntities: Option[Seq[MessageEntity]],
  contact: Option[Contact],
  dice: Option[Dice],
  game: Option[Game],
  poll: Option[Poll],
  venue: Option[Venue],
  location: Option[Location],
  newChatMembers: Option[Seq[User]],
  leftChatMember: Option[User],
  newChatTitle: Option[String],
  newChatPhoto: Option[Seq[PhotoSize]],
  deleteChatPhoto: Option[Boolean],
  groupChatCreated: Option[Boolean],
  supergroupChatCreated: Option[Boolean],
  channelChatCreated: Option[Boolean],
  messageAutoDeleteTimerChanged: Option[MessageAutoDeleteTimerChanged],
  migrateToChatId: Option[Long],
  migrateFromChatId: Option[Long],
  pinnedMessage: Option[Message],
  invoice: Option[Invoice],
  successfulPayment: Option[SuccessfulPayment],
  connectedWebsite: Option[String],
  passportData: Option[PassportData],
  proximityAlertTriggered: Option[ProximityAlertTriggered],
  videoChatScheduled: Option[VideoChatScheduled],
  videoChatStarted: Option[VideoChatStarted],
  videoChatEnded: Option[VideoChatEnded],
  videoChatParticipantsInvited: Option[VideoChatParticipantsInvited],
  webAppData: Option[WebAppData],
  replyMarkup: Option[InlineKeyboardMarkup]
)
