package com.github.aalbul.zio.telegram.domain

import io.circe.generic.extras.ConfiguredJsonCodec

import java.time.Instant

object Message {
  def of(messageId: Int, date: Instant, chat: Chat): Message = Message(
    messageId = messageId,
    from = None,
    senderChat = None,
    date = date,
    chat = chat,
    forwardFrom = None,
    forwardFromChat = None,
    forwardFromMessageId = None,
    forwardSignature = None,
    forwardSenderName = None,
    forwardDate = None,
    isAutomaticForward = None,
    replyToMessage = None,
    viaBot = None,
    editDate = None,
    hasProtectedContent = None,
    mediaGroupId = None,
    authorSignature = None,
    text = None,
    entities = None,
    animation = None,
    audio = None,
    document = None,
    photo = None,
    sticker = None,
    video = None,
    videoNote = None,
    voice = None,
    caption = None,
    captionEntities = None,
    contact = None,
    dice = None,
    game = None,
    poll = None,
    venue = None,
    location = None,
    newChatMembers = None,
    leftChatMember = None,
    newChatTitle = None,
    newChatPhoto = None,
    deleteChatPhoto = None,
    groupChatCreated = None,
    supergroupChatCreated = None,
    channelChatCreated = None,
    messageAutoDeleteTimerChanged = None,
    migrateToChatId = None,
    migrateFromChatId = None,
    pinnedMessage = None,
    invoice = None,
    successfulPayment = None,
    connectedWebsite = None,
    passportData = None,
    proximityAlertTriggered = None,
    videoChatScheduled = None,
    videoChatStarted = None,
    videoChatEnded = None,
    videoChatParticipantsInvited = None,
    webAppData = None,
    replyMarkup = None
  )
}

@ConfiguredJsonCodec(decodeOnly = true)
case class Message(
  messageId: Int,
  from: Option[User],
  senderChat: Option[Chat],
  date: Instant,
  chat: Chat,
  forwardFrom: Option[User],
  forwardFromChat: Option[Chat],
  forwardFromMessageId: Option[Int],
  forwardSignature: Option[String],
  forwardSenderName: Option[String],
  forwardDate: Option[Instant],
  isAutomaticForward: Option[Boolean],
  replyToMessage: Option[Message],
  viaBot: Option[User],
  editDate: Option[Instant],
  hasProtectedContent: Option[Boolean],
  mediaGroupId: Option[String],
  authorSignature: Option[String],
  text: Option[String],
  entities: Option[Seq[MessageEntity]],
  animation: Option[Animation],
  audio: Option[Audio],
  document: Option[Document],
  photo: Option[Seq[PhotoSize]],
  sticker: Option[Sticker],
  video: Option[Video],
  videoNote: Option[VideoNote],
  voice: Option[Voice],
  caption: Option[String],
  captionEntities: Option[Seq[MessageEntity]],
  contact: Option[Contact],
  dice: Option[Dice],
  game: Option[Game],
  poll: Option[Poll],
  venue: Option[Venue],
  location: Option[Location],
  newChatMembers: Option[Seq[User]],
  leftChatMember: Option[User],
  newChatTitle: Option[String],
  newChatPhoto: Option[Seq[PhotoSize]],
  deleteChatPhoto: Option[Boolean],
  groupChatCreated: Option[Boolean],
  supergroupChatCreated: Option[Boolean],
  channelChatCreated: Option[Boolean],
  messageAutoDeleteTimerChanged: Option[MessageAutoDeleteTimerChanged],
  migrateToChatId: Option[Long],
  migrateFromChatId: Option[Long],
  pinnedMessage: Option[Message],
  invoice: Option[Invoice],
  successfulPayment: Option[SuccessfulPayment],
  connectedWebsite: Option[String],
  passportData: Option[PassportData],
  proximityAlertTriggered: Option[ProximityAlertTriggered],
  videoChatScheduled: Option[VideoChatScheduled],
  videoChatStarted: Option[VideoChatStarted],
  videoChatEnded: Option[VideoChatEnded],
  videoChatParticipantsInvited: Option[VideoChatParticipantsInvited],
  webAppData: Option[WebAppData],
  replyMarkup: Option[InlineKeyboardMarkup]
)
